services:
  - type: cron
    name: leetcode-sms
    runtime: docker
    schedule: "0 13,1 * * *" # Cron schedule for 5 AM and 5 PM PST (converted to UTC)
    autoDeploy: false
    repo: https://github.com/tkruer/leetcode-sms-reminder.git
    
envVarGroups:
  - name: conc-settings
    envVars:
      - key: CONCURRENCY
        value: 2
      - key: SECRET
        generateValue: true
      - key: USER_PROVIDED_SECRET
        sync: false