services:
  - type: cron
    name: leetcode-sms
    runtime: docker
    schedule: "0 13,1 * * *" # Cron schedule for 5 AM and 5 PM PST (converted to UTC)
    autoDeploy: false
    
envVarGroups:
  - name: CHANGE_ME_SMS_ENV
    envVars:
      - key: YOUR_PHONE_NUMBER
        value: 1234567890
        sync: true
      - key: TWILLIO_ACCOUNT_SID
        value: YOUR_TWILLIO_ACCOUNT_SID
        sync: true
      - key: TWILLIO_AUTH_TOKEN
        value: YOUR_TWILLIO_AUTH_TOKEN
        sync: true
      - key: TWILLIO_PHONE_NUMBER
        value: YOUR_TWILLIO_PHONE_NUMBER
        sync: true
 