services:
  - type: cron
    name: your-cron-job-name
    dockerfilePath: ./Dockerfile
    schedule: "0 13,1 * * *" # Cron schedule for 5 AM and 5 PM PST (converted to UTC)
    plan: starter
    autoDeploy: false